### ISSUE TITLE
Fix infinite dezoom bug

### ISSUE THREAD

**Issue by VictorGrabowski** [dipu-s-repo68/hacktoberfest2024_second.github.io#4]
At the moment you can zoom infinetly inside and outside.

a curious behaviour occurs when we unzoom too far, it zooms back in at a certain point. 

proposition ->
Fix a max unzoom amount and a max zoom-it amount, make something to slow down zoom progressivly

**Comment by dipu-s-repo68** [comment]
@VictorGrabowski fix it

**Comment by VictorGrabowski** [comment]
i dont have the rights to create a branch, i made the changes locally, waiting to be able to push them

**Comment by VictorGrabowski** [comment]
Sorry it was my first contribution on an open source project, i did not know how to contribute, i forked the project and created the pr, sorry for the inconvenience
